services:
  - type: web
    name: illara-api
    env: node
    rootDir: apps/api
    plan: free
    region: frankfurt
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: node dist/index.js
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
